{% set name = "xpdan" %}
{% set version = "0.8.1" %}
{% set sha256 = "cb63b959f15811a30e8f590c29649425dd81145622efbd3119ef314b6d988ea8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/xpdAn-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 3
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - scipy
    - matplotlib
    - pyyaml
    - scikit-beam
    - pyfai
    - xray-vision
    - databroker
    - bluesky
    - rapidz
    - xpdsim
    - shed
    - xpdview
    - ophyd
    - xpdconf
    - xpdtools

test:
  imports:
    - xpdan
    - xpdan.pipelines

about:
  home: http://github.com/xpdAcq/xpdAn
  license: BSD-3-Clause 
  license_family: BSD
  license_file: LICENSE
  summary: 'Analysis Tools for XPD'
  doc_url: http://xpdacq.github.io/xpdAn/
  dev_url: http://github.com/xpdAcq/xpdAn

extra:
  recipe-maintainers:
    - CJ-Wright
