{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: 12-id-smi-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - pyfai
    - sasview
