{% set version = "1.5.0" %}

package:
    name: tomopy
    version: {{ version }}

source:
  # Switched to git checkout because of PTL submodule
  git_url: https://github.com/tomopy/tomopy.git
  git_rev: {{ version }}

build:
  number: 0
  skip: true  # [win and py2k]
  merge_build_host: True  # [win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --install-option="-GNinja"
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('cxx') }}
    - git
  host:
    - pip
    - python
    - libopencv
    - mkl-devel
    - scikit-build
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - futures  # [py2k]
    - mkl
    - mkl_fft
    - numexpr
    - numpy
    - libopencv
    - pywavelets
    - python
    - scikit-image
    - scipy<1.3
    - six
    - tifffile

test:
  requires:
    - nose
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - nosetests test

app:
    own_environment: True

about:
    home: http://tomopy.readthedocs.io
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: 'Tomographic reconstruction in Python.'
    description: |
      TomoPy is an open-source Python package for tomographic data processing
      and image reconstruction.
    doc_url: http://tomopy.readthedocs.io
    dev_url: https://github.com/tomopy/tomopy

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - licode
        - ravescovi
        - tacaswell
        - oleksandr-pavlyk
        - carterbox
