{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: 28-id-2-xpd-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - xpdan
    - bluesky
    - databroker
