{% set year = "17" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: 16-id-lix-analysis
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - fabio
    - py4xs
    - lmfit >=0.9.9
    - peakutils
